name: docs-ci
on:
  push:
    branches:
      - master
jobs: 
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull request
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
          ACCESS_NAME: ${{ secrets.ACCESS_USERNAME }}
        run: |
          npm install
          npm run pr
        